// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDshN-UJsSLK38GMw9CUrIIXdH_-DLTJSU',
    appId: '1:128974071888:web:8d511ff55cc516d3efc955',
    messagingSenderId: '128974071888',
    projectId: 'e-commerce-26a43',
    authDomain: 'e-commerce-26a43.firebaseapp.com',
    storageBucket: 'e-commerce-26a43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjfd7coWI51LlepQ6N0l3y5A1ppUgKlU',
    appId: '1:128974071888:android:eaae7112b8ec20eaefc955',
    messagingSenderId: '128974071888',
    projectId: 'e-commerce-26a43',
    storageBucket: 'e-commerce-26a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM3fK-cSMoZZL41OwewJx1iy9go9EP5xY',
    appId: '1:128974071888:ios:0e980bc205c874ceefc955',
    messagingSenderId: '128974071888',
    projectId: 'e-commerce-26a43',
    storageBucket: 'e-commerce-26a43.appspot.com',
    androidClientId: '128974071888-gb8nlo3a7pro8ahsp9u5bce8udiump2k.apps.googleusercontent.com',
    iosClientId: '128974071888-a5h5otugaqfrc1fraqiq2jf20b6oeqaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM3fK-cSMoZZL41OwewJx1iy9go9EP5xY',
    appId: '1:128974071888:ios:0e980bc205c874ceefc955',
    messagingSenderId: '128974071888',
    projectId: 'e-commerce-26a43',
    storageBucket: 'e-commerce-26a43.appspot.com',
    androidClientId: '128974071888-gb8nlo3a7pro8ahsp9u5bce8udiump2k.apps.googleusercontent.com',
    iosClientId: '128974071888-a5h5otugaqfrc1fraqiq2jf20b6oeqaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceV2',
  );
}
